services:
  - type: web
    plan: free
    name: django-app
    runtime: python3
    repo: https://github.com/Dant22/pages.git
    buildCommand: pip install -r requirements.txt
    # startCommand: 'python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker'
    startCommand: gunicorn django_project.wsgi
    Instance Type: Free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
#     PORT: "3000"
#     envVars:
#       - key: DATABASE_URL
#         fromDatabase:
#           name: django-app-db
#           property: connectionString

# databases:
#   - name: django-app-db
#     plan: free